branches:
  only:
  - master
language: python
sudo: false
noticications:
  email: false
python:
- 2.7
install:
- wget http://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
- bash miniconda.sh -b -p $HOME/conda
- export PATH="$HOME/conda/bin:$PATH"
- conda config --set always_yes yes
- conda install pyyaml
- conda info -a
- conda env create
- export PATH="$HOME/conda/envs/blog/bin:$PATH"
- conda list
script:
- make html
after_success: bash deploy.sh
env:
  global:
  - secure: GFXNLaULz0MSfIMIdo0LlXogNFx/UmNCkrx4IDZXprxLy8SxM9s6EQFA1+FtXzYfegpScD7QvDit0D08EoDn93n7tFwTar5y2fARFtgiH0vjgPUNNigsjn7uXYGIoVKa9k370qiXJEfJB5bS+gKICrC6RVzVtwmRcUlmQhJFuRNQA8SJEzLiYH64Www2fYS5gfagxVFFykOXRHHELv0Dnzbacc1fDs1PvVVjG1bSD9niSYtM4r0cWL0fXTe3NCchBHsYVbCUm0+e8CN4owyh2aBJUX9UeL7BKgkBTT90rF6EMCelUPZv8jnMznLGkW0KSJtsd/L4nDrkJyA/zc93j+eDY4HerrYqTL1Nxj6u9AWCtUXIXbpQSLor6pWLNTH1ST1+SZwXokChCHSp+tjragiiV/NTfbMGYtD9HhAiA3AYKyjvA0Tlf/B81QRd+gvwLa7vBz2AwlGSm+iluqsK4gkecJKZaxTR62tjmxoW6c99J/K+IyWXwgE4qyL4rgww0A2cvvZZ1sHx99mOvRqzP68lWaanH3uDDl7WLlNymwE3dF4DmwBf/9q3Gz/YsTQEUlNotnFjSifi+s1j64j7EMVTK6MEXKWpSt/3C5nVh8MoAFnd6/CBohO2H08iYRv5r1rAFJaJJhB6fLgxZ/kDMy0jjaH8G1kCxm83Wftkrf4=
